apiVersion: 1

datasources:
  - name: Weather PostgreSQL
    uid: weather-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    isDefault: true
    editable: true
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable  
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
